config/routes.rb
Rails.application.routes.draw do
  get "dashboard/index" # You might consider removing this if 'root 'pages#home'' serves as your main dashboard.
  ##Uncomment if there is an issue
    #get 'transactions/index'
    #get 'transactions/new'
    #get 'transactions/create'
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'signup'
  }, controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }

  get 'dashboard/statistics', to: 'dashboard#statistics'

  # Custom profile route
  get '/u/:id', to: 'users#profile', as: 'user'

  # Static pages
  get 'about', to: 'pages#about'

  # Health check
  get 'up', to: 'rails/health#show', as: :rails_health_check

  # config/routes.rb (This line seems to be misplaced or redundant if you have posts resources already)
  get "posts/loan_calculation", to: "posts#loan_calculation" # Consider if this is needed or if it should be within resources :posts do ... end

  # config/routes.rb (This line seems to be misplaced or redundant if you have posts resources already)
  get "posts/loan_calculation", to: "posts#loan_calculation" # Consider if this is needed or if it should be within resources :posts do ... end

  # Transactions custom routes
  # Optional shortcut route
  get 'transelect', to: redirect('/transactions/transelect')

# Transactions custom routes
  get 'transactions/transelect', to: 'transactions#transelect', as: 'transelect_post'
  get 'transactions/start', to: 'transactions#start_transaction', as: 'start_transaction'


  resources :posts do
    member do
      patch :approve
      patch :reject
      post :validate
    end
  end

  resources :transactions, only: [:index, :new, :create]

  resources :credit_cards, except: [:show, :new, :loanselect]
  get 'loanselect', to: 'posts#loanselect', as: 'loanselect_post' # This `loanselect` action belongs in PostsController
  resources :transactions, only: [:index, :new, :create]

  # CORRECTED: Calculator routes now point to CalculatorController
  get 'interest_calculator', to: 'calculator#interest', as: :interest_calculator
  post 'calculate_interest', to: 'calculator#calculate_interest', as: :calculate_interest

  # CORRECTED: Penalty Calculator routes now point to CalculatorController
  get 'penalty_calculator', to: 'calculator#penalty', as: :penalty_calculator
  post 'calculate_penalty', to: 'calculator#calculate_penalty', as: :calculate_penalty

  # Overdues route
  get 'overdues', to: 'pages#overdues', as: :overdues

  # API Routes (JSON)
  scope '/api', defaults: { format: :json } do
    scope '/v1' do
      devise_for :users,
        path: '',
        path_names: { sign_in: 'login', sign_out: 'logout' },
        controllers: {
          registrations: 'registrations',
          sessions: 'sessions'
        },
        as: :api_v1

      devise_scope :user do
        get 'users/current', to: 'sessions#show'
      end

      resources :pages, only: [:index]
    end
  end

  # Root path
  root 'pages#home'
end

# NOTE: This `def loanselect` should NOT be in routes.rb.
# It should be a method inside your PostsController.
# def loanselect
#   # logic for loan selection page
# end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def profile
    @user.update(views: @user.views + 1)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_session_manager.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <span><%= current_user.email   %></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
      <li>
        <%= link_to "New Post", new_post_path, class: "dropdown-item" %>
      </li>
      <li>
        <%= link_to "Profile", "#", class: "dropdown-item" %>
      </li>
      <li>
        <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item", form: { "data-turbo-confirm": "Are you sure you want to sign out?" } %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Login", new_user_session_path, class: "nav-link" %>
  </li>
<% end %>

app/views/user/profile.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm py-2">
  <div class="container-fluid">
    <%= link_to "🚀 MyDashboard", root_path, class: "navbar-brand fw-bold text-gradient fs-2" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="postsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-file-earmark-text me-1"></i> Posts
          </a>
          <ul class="dropdown-menu" aria-labelledby="postsDropdown">
            <li><%= link_to "All Posts", posts_path, class: "dropdown-item" %></li>
            <li><%= link_to "New Post", new_post_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="supportDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-life-preserver me-1"></i> Support
          </a>
          <ul class="dropdown-menu" aria-labelledby="supportDropdown">
            <li><%= link_to "Tickets", tickets_path, class: "dropdown-item" %></li>
            <li><%= link_to "Credit Cards", credit_cards_path, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="navbarUserDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle me-1 fs-5"></i>
              <span class="fw-semibold"><%= current_user.email %></span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarUserDropdown">
              <li><%= link_to "Profile", user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item text-danger" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary ms-2 px-4" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<style>
  .text-gradient {
    background: linear-gradient(90deg, #0d6efd 0%, #6610f2 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    text-fill-color: transparent;
  }
</style>

<h1><%= @user.email %></h1>
<h6><%= pluralize(@users.views, "view") %></h6>
<p>Find me in app/views/user/profile.html.erb</p>